// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woulrjxckivziwsjzzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvdWxyanhja2l2eml3c2p6enZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODI0MDEsImV4cCI6MjA2MTE1ODQwMX0.28cKwiZ6llYtOSzOaC4CLed6dRbQMEFT__QHl8KfR5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);